language: node_js
node_js:
  - 16.0.0
script: npm run test
after_script: npm run cover && cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
env:
  global:
    secure: U8Zd1z5E3/ovD87OpBWxMm0xCNcl1mqOM+cWKgTmOJlTPVHLCVA7G9oZd8i1K7trW6fDvTJT1GW5ZNzBOV8+bYEVUeTeqAvtgiqZLLVC2IEdmfXsumvsprC8OuCKHh8d7lNhn1vCGXGGLllO2J3tG66ATjQ2ZgdqPBUQ20mafqy4OOGkqs7PcvV1A7OMQnFNpPL6bptpxiumCdHUSirsM48e0dFRPNVfxPVYbKitil0Q+sWUh+HebTpEIdyiKMjTepJaGuIVIsKnWhIHT2qN5BI7n/pjQLkq7C53MkGTAtCz9CP+W1Sr2rJmE493ClefacZI7kQovc3lPzVE/oyWNdNQT3eRx/bI4G34A9vetAvMtMX00mC8syeb1Y3QzCMOgDT9K9QPLtMD9iX9Xfa7+Rqjfe1FVta7QLkcXd1TMDuNSj7imfHMYqj82sxXVGGyQObRfgkhYrVNi02JhdcucPO01UQxLWtoynoRL8Qop1L/dyECp/t4QpRFQJcSDVVLXQLTKxnj842ghhvGRXdm47MovlzrhYa05pCKuJMWLMH7H6TGUF/iSHX9b2N/efijBtxmlX+a8BKVk8wEy/BZchPugYrlKvJw6WhfMqjmS6V8mqP5gdWlz3jjrDLDWzb9/2EtXyuiHdudOsxEi9PPBHmdpcZYuePg3qogfJX/EII=
